In [1]:
import torch 

### **unsqueeze()**: change the dimension of the tensor but content is the same 

In [7]:
n = torch.tensor([1,2,3,4,5])
print("original tensor: ", n)
print("original shape: ", n.shape)
# want to change the shape from [5] to [1,5]
# --> need to add a new dimention in the dim0
n0 = torch.unsqueeze(n,0) 
print("[1,5] tensor: ", n0)
print("[1,5] shape: ", n0.shape)
# want to change the shape from [5] to [5,1]
# --> need to add a new dimention in the dim1
n1 = torch.unsqueeze(n,1) 
print("[5,1] tensor: \n", n1)
print("[5,1] shape: ", n1.shape)


original tensor:  tensor([1, 2, 3, 4, 5])
original shape:  torch.Size([5])
[1,5] tensor:  tensor([[1, 2, 3, 4, 5]])
[1,5] shape:  torch.Size([1, 5])
[5,1] tensor: 
 tensor([[1],
        [2],
        [3],
        [4],
        [5]])
[5,1] shape:  torch.Size([5, 1])


## expand(): copy one or more dimentions to create a new matrix 

In [21]:
#if i want to create a 5*5 matrix with the same row 
#--> use the n0, and then expand 
n_55=n0.expand(5,-1)
print("n_55 shape: ", n_55.shape)
print("n_55 tensor: \n", n_55)

# we don't need to first unsqueeze the tensor from 1 dim to 2 dim and then do the expand. 
n_test = n.expand(5,5)
print(n.shape)
print(n)
print(n_test.shape)
print(n_test)
#but if we don't do unsqueeze, we can't let the 1,2,3,4,5 to be the column 
n_55_col = n1.expand(-1,5)
print(n_55_col)

n_55 shape:  torch.Size([5, 5])
n_55 tensor: 
 tensor([[1, 2, 3, 4, 5],
        [1, 2, 3, 4, 5],
        [1, 2, 3, 4, 5],
        [1, 2, 3, 4, 5],
        [1, 2, 3, 4, 5]])
torch.Size([5])
tensor([1, 2, 3, 4, 5])
torch.Size([5, 5])
tensor([[1, 2, 3, 4, 5],
        [1, 2, 3, 4, 5],
        [1, 2, 3, 4, 5],
        [1, 2, 3, 4, 5],
        [1, 2, 3, 4, 5]])
tensor([[1, 1, 1, 1, 1],
        [2, 2, 2, 2, 2],
        [3, 3, 3, 3, 3],
        [4, 4, 4, 4, 4],
        [5, 5, 5, 5, 5]])


## **cat()** choose a dimension and add the elements in that dimension together.

In [24]:
x = torch.randn(2, 3)
x1 = torch.cat((x,x,x),1) 
print(x1)
##--> the 1 here means add the dimestion 1 elemets together 
## the shape of x is (2,3), if you add 3 of x together --> (2,3+3+3) which is (2,9)

x2=torch.cat((x,x,x), 0)
print(x2)
## add the dimension 0 together: so the result would be (2+2+2,3) which is (6,3)

tensor([[-0.0250, -0.0272,  0.8918, -0.0250, -0.0272,  0.8918, -0.0250, -0.0272,
          0.8918],
        [-1.1294,  0.7870,  0.7758, -1.1294,  0.7870,  0.7758, -1.1294,  0.7870,
          0.7758]])
tensor([[-0.0250, -0.0272,  0.8918],
        [-1.1294,  0.7870,  0.7758],
        [-0.0250, -0.0272,  0.8918],
        [-1.1294,  0.7870,  0.7758],
        [-0.0250, -0.0272,  0.8918],
        [-1.1294,  0.7870,  0.7758]])


## **sum()** add the elements in one dimention together. add the elements in thar dim together, and the shape of the matrix after sum will become smaller the sum target dim will disapear 

In [31]:
a = torch.randn(2,3)
print(a)
print(a.shape)
## add the dim 1 elements together 
## the shape after sum() will become [2]
a1 = torch.sum(a,1)
print(a1) 
print(a1.shape)

a0 = torch.sum(a,0)
print(a0)
print(a0.shape)

a2 = torch.sum(a,-1) ## -1 mean add the last dimension
print(a2)


tensor([[ 1.2766,  0.1574,  0.7136],
        [ 0.1817, -0.9922, -1.7358]])
torch.Size([2, 3])
tensor([ 2.1476, -2.5463])
torch.Size([2])
tensor([ 1.4583, -0.8348, -1.0222])
torch.Size([3])
tensor([ 2.1476, -2.5463])
